import Item from '@/utils/item'

export class Plot extends Item {
  constructor (item) {
    super()

    this.item = {
      ...this.createProperty(item, 'id'),
      ...this.createProperty(item, 'identifier', 'id'),
      ...this.createProperty(item, 'farmer'),
      ...this.createProperty(item, 'polygon_id'),
      ...this.createProperty(item, 'farmer_id'),
      ...this.createNumber(item, 'area_m2', 0),
      ...this.createProperty(item, 'project'),
      ...this.createProperty(item, 'species_id'),
      ...this.createProperty(item, 'species'),
      ...this.createProperty(item, 'species_id'),
      ...this.createInteger(item, 'survey_count'),
      ...this.createDateSubstring(item, 'latest_survey_date'),
      ...this.createTime(item, 'latest_survey_date_sortable', 'latest_survey_date'),
      ...this.createInteger(item, 'latest_survey_treecount'),
      ...this.createProperty(item, 'latest_survey_dbh_mean'),
      ...this.createFloat(item, 'latest_survey_dbh_mean_sortable', 'latest_survey_dbh_mean'),
      ...this.createProperty(item, 'latest_survey_height_mean'),
      ...this.createFloat(item, 'latest_survey_height_mean_sortable', 'latest_survey_height_mean'),
      ...this.createProperty(item, 'latest_survey_tree_volume'),
      ...this.createFloat(item, 'latest_survey_tree_volume_sortable', 'latest_survey_tree_volume'),
      ...this.createNumber(item, 'latest_survey_value_ird', 0),
      ...this.createFloat(item, 'latest_survey_value_ird_sortable', 'latest_survey_value_ird'),
      ...this.createNumber(item, 'latest_survey_value_usd', 2),
      ...this.createFloat(item, 'latest_survey_value_usd_sortable', 'latest_survey_value_usd'),
      ...this.createProperty(item, 'trees_per_ha'),
      ...this.createProperty(item, 'soil_type'),
      ...this.createProperty(item, 'soil_type_id'),
      ...this.createProperty(item, 'legal_status'),
      ...this.createProperty(item, 'legal_status_id'),
      ...this.createProperty(item, 'village'),
      ...this.createProperty(item, 'village_id'),
      ...this.createProperty(item, 'district'),
      ...this.createProperty(item, 'planting_distance'),
      ...this.createProperty(item, 'planting_distance_id'),
      ...this.createProperty(item, 'field_coordinator'),
      ...this.createProperty(item, 'field_coordinator_id'),
      ...this.createProperty(item, 'supporter'),
      ...this.createProperty(item, 'supporter_id'),
      ...this.createProperty(item, 'nursery'),
      ...this.createProperty(item, 'nursery_id'),
      ...this.createProperty(item, 'planting_date'),
      ...this.createProperty(item, 'video_url'),
      ...this.createProperty(item, 'neighbors'),
      ...this.createProperty(item, 'landscape_features'),
      ...this.createProperty(item, 'general_conditions'),
      ...this.createProperty(item, 'fire_fighting'),
      active: item.active,
      sample: item.sample,
      ...this.createProperty(item, 'plants_planted'),
      ...this.createDate(item, 'created_at'),
      ...this.createDate(item, 'updated_at'),
    }
  }
}
